[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nlp-sql-api"
version = "1.0.0"
description = "NLP to SQL API"
requires-python = ">=3.12.6"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn[standard]>=0.24.0",
    "psycopg[binary]>=3.1.0",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
    "python-multipart>=0.0.6",
    "pydantic>=2.5.0",
    "pandas>=2.1.0",
    "supabase==2.18.1",
    "email-validator==2.1.1",
    "PyJWT==2.10.1"
]